version: '3'
services:
  api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ".:/opt/app"
    container_name: api
    command: python /opt/app/app.py >> /dev/null
    environment:
      - TOKEN="${TOKEN}"